name: pokemon_quiz
description: A Pokémon quiz app made with Flutter.
publish_to: 'none'  # 공개 패키지로 배포 안 할 때 설정

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0  # ✅ 추가

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
