name: pokemon_quiz
description: A Pokémon quiz app made with Flutter.
publish_to: 'none'  # 공개 패키지로 배포 안 할 때 설정

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 필요한 패키지 있으면 추가 가능
  # 예) cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

#  assets:
#    - assets/images/pokeball.png
